name: "destroy staging environment aws resources"
on:
    workflow_dispatch:
        inputs:
            PR_number:
                description: 'Pull Request Number'
                required: true
jobs:
    destroy_staging:
        name: Destroy Staging environment
        environment: staging
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Setup Terraform
              run: |
                echo "You are now rocking with the best"