name: Create staging environment for push request to test site

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull Request Number'
        required: true

jobs:
  create_staging:
    name: Create Staging environment
    environment: staging
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
        shell: bash

    steps:
      # ======================================================
      # It's important to check that the PR number provided as input is valid and belongs to the repository.
      # 
      # This will also return the PR's branch as an output which can be fetched in next steps via:
      # ${{ steps.verify_pr_number.outputs.result }}
      # ======================================================
      - name: Verify Pull Request Number
        uses: actions/github-script@v7
        id: verify_pr_number
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ github.event.inputs.PR_number }}
            });

            // Check if the pull request is open
            if (response.data.number !== ${{ github.event.inputs.PR_number }}) {
                throw new Error('Pull request is not open or number is not valid!');
            } else {
                console.log("PR ref: " + response.data.head.ref);
                return response.data.head.ref;
            }

      - name: Checkout the repo
        uses: actions/checkout@v4