version: "3.8"

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile.dev.nodejs
    container_name: node_app
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      NODE_ENV: development
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
